# Broadcasting in Python
Author: Geovanna Santos Nobre de Oliveira

In [1]:
import numpy as np

In [2]:
A = np.array([
    [56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
# Total calories in each source
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
# Calculate the percentage using broadcasting
percentage = np.round(100*A/cal.reshape(1,4), 2)
print(percentage)

[[94.92  0.    2.83 88.43]
 [ 2.03 43.51 33.46 10.4 ]
 [ 3.05 56.49 63.71  1.17]]


Another simples examples

In [5]:
B = np.array([
    [1],
    [2],
    [3],
    [4]
])
print(B)

[[1]
 [2]
 [3]
 [4]]


In [6]:
# Here the 100 will be copied four times to become a (4,1) matrix
B2 = B + 100
print(B2)

[[101]
 [102]
 [103]
 [104]]


In [7]:
C = np.array([
    [1,2,3],
    [4,5,6]
])
print(C)

[[1 2 3]
 [4 5 6]]


In [8]:
# Here the matrix [100, 200, 300] will be copied two times to become a (2,3) matrix
C2 = C + [100, 200, 300]
print(C2)

[[101 202 303]
 [104 205 306]]


In [9]:
D = np.array([
    [1,2,3],
    [4,5,6]
])
print(D)

[[1 2 3]
 [4 5 6]]


In [10]:
# Here the matrix [[100], [200]] will be copied three times to become a (2,3) matrix
D2 = D + np.array([[100],[200]])
print(D2)

[[101 102 103]
 [204 205 206]]
